//
// OrganizationAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class OrganizationAPI {

    /**
     Onboarding Config
     
     - parameter xOnboardingConfigKey: (header)  
     - parameter openAPIClient: The OpenAPIClient that contains the configuration for the http request.
     - returns: PublicOnboardingConfiguration
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getOnboardingConfig_0(xOnboardingConfigKey: String, openAPIClient: OpenAPIClient = OpenAPIClient.shared) async throws(ErrorResponse) -> PublicOnboardingConfiguration {
        return try await getOnboardingConfig_0WithRequestBuilder(xOnboardingConfigKey: xOnboardingConfigKey, openAPIClient: openAPIClient).execute().body
    }

    /**
     Onboarding Config
     - GET /hosted/onboarding/config
     - Get the details of an onboarding configuration.
     - API Key:
       - type: apiKey X-Onboarding-Config-Key (HEADER)
       - name: OnboardingConfigPublishableKey
     - API Key:
       - type: apiKey X-Onboarding-Session-Token (HEADER)
       - name: OnboardingConfigToken
     - API Key:
       - type: apiKey X-Kyb-Bo-Token (HEADER)
       - name: BusinessOwnerToken
     - API Key:
       - type: apiKey X-Fp-Authorization (HEADER)
       - name: UserToken
     - parameter xOnboardingConfigKey: (header)  
     - parameter openAPIClient: The OpenAPIClient that contains the configuration for the http request.
     - returns: RequestBuilder<PublicOnboardingConfiguration> 
     */
    open class func getOnboardingConfig_0WithRequestBuilder(xOnboardingConfigKey: String, openAPIClient: OpenAPIClient = OpenAPIClient.shared) -> RequestBuilder<PublicOnboardingConfiguration> {
        let localVariablePath = "/hosted/onboarding/config"
        let localVariableURLString = openAPIClient.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Onboarding-Config-Key": xOnboardingConfigKey.encodeToJSON(codableHelper: openAPIClient.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PublicOnboardingConfiguration>.Type = openAPIClient.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, openAPIClient: openAPIClient)
    }
}
