//
// AuthMethod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AuthMethod: Codable, JSONEncodable, Hashable {

    public enum Kind: String, Codable, CaseIterable {
        case phone = "phone"
        case passkey = "passkey"
        case email = "email"
    }
    /** True if the user's auth token doesn't restrict updating this auth method */
    public var canUpdate: Bool
    public var isVerified: Bool
    public var kind: Kind

    public init(canUpdate: Bool, isVerified: Bool, kind: Kind) {
        self.canUpdate = canUpdate
        self.isVerified = isVerified
        self.kind = kind
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case canUpdate = "can_update"
        case isVerified = "is_verified"
        case kind
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(canUpdate, forKey: .canUpdate)
        try container.encode(isVerified, forKey: .isVerified)
        try container.encode(kind, forKey: .kind)
    }
}

