//
// AuthRequirementsResponseAllRequirementsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AuthRequirementsResponseAllRequirementsInner: Codable, JSONEncodable, Hashable {

    public var isMet: Bool

    public init(isMet: Bool) {
        self.isMet = isMet
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isMet = "is_met"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(isMet, forKey: .isMet)
    }
}

