//
// CheckSessionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum CheckSessionResponse: String, Codable, CaseIterable {
    case active = "active"
    case expired = "expired"
    case unknown = "unknown"
}
