//
// CollectDataRequirement.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CollectDataRequirement: Codable, JSONEncodable, Hashable {

    public enum Kind: String, Codable, CaseIterable {
        case collectData = "collect_data"
    }
    public var kind: Kind
    public var isMet: Bool
    public var missingAttributes: [CollectedAttributes]
    public var optionalAttributes: [CollectedAttributes]
    public var populatedAttributes: [CollectedAttributes]

    public init(kind: Kind, isMet: Bool, missingAttributes: [CollectedAttributes], optionalAttributes: [CollectedAttributes], populatedAttributes: [CollectedAttributes]) {
        self.kind = kind
        self.isMet = isMet
        self.missingAttributes = missingAttributes
        self.optionalAttributes = optionalAttributes
        self.populatedAttributes = populatedAttributes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case kind
        case isMet = "is_met"
        case missingAttributes = "missing_attributes"
        case optionalAttributes = "optional_attributes"
        case populatedAttributes = "populated_attributes"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(kind, forKey: .kind)
        try container.encode(isMet, forKey: .isMet)
        try container.encode(missingAttributes, forKey: .missingAttributes)
        try container.encode(optionalAttributes, forKey: .optionalAttributes)
        try container.encode(populatedAttributes, forKey: .populatedAttributes)
    }
}

