//
// CollectedAttributes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum CollectedAttributes: String, Codable, CaseIterable {
    case name = "name"
    case dob = "dob"
    case ssn4 = "ssn4"
    case ssn9 = "ssn9"
    case fullAddress = "full_address"
    case email = "email"
    case phoneNumber = "phone_number"
    case nationality = "nationality"
    case usLegalStatus = "us_legal_status"
    case usTaxId = "us_tax_id"
    case investorProfile = "investor_profile"
}
