//
// FingerprintVisitRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FingerprintVisitRequest: Codable, JSONEncodable, Hashable {

    public var path: String
    public var requestId: String
    public var visitorId: String

    public init(path: String, requestId: String, visitorId: String) {
        self.path = path
        self.requestId = requestId
        self.visitorId = visitorId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case path
        case requestId = "request_id"
        case visitorId = "visitor_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(path, forKey: .path)
        try container.encode(requestId, forKey: .requestId)
        try container.encode(visitorId, forKey: .visitorId)
    }
}

