//
// GetSdkArgsTokenResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetSdkArgsTokenResponse: Codable, JSONEncodable, Hashable {

    public var args: String
    public var obConfig: GetSdkArgsTokenResponseObConfig?

    public init(args: String, obConfig: GetSdkArgsTokenResponseObConfig? = nil) {
        self.args = args
        self.obConfig = obConfig
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case args
        case obConfig = "ob_config"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(args, forKey: .args)
        try container.encodeIfPresent(obConfig, forKey: .obConfig)
    }
}

