//
// HostedBusinessInviter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The primary business owner that invited you to fill out a KYC form */
public struct HostedBusinessInviter: Codable, JSONEncodable, Hashable {

    public var firstName: String
    public var lastName: String

    public init(firstName: String, lastName: String) {
        self.firstName = firstName
        self.lastName = lastName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case firstName = "first_name"
        case lastName = "last_name"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(firstName, forKey: .firstName)
        try container.encode(lastName, forKey: .lastName)
    }
}

