//
// HostedBusiness.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct HostedBusiness: Codable, JSONEncodable, Hashable {

    public var invited: HostedBusinessInvited
    public var inviter: HostedBusinessInviter
    public var name: String

    public init(invited: HostedBusinessInvited, inviter: HostedBusinessInviter, name: String) {
        self.invited = invited
        self.inviter = inviter
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case invited
        case inviter
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(invited, forKey: .invited)
        try container.encode(inviter, forKey: .inviter)
        try container.encode(name, forKey: .name)
    }
}

