//
// IdentifyResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct IdentifyResponse: Codable, JSONEncodable, Hashable {

    public var user: IdentifyResponseUser?

    public init(user: IdentifyResponseUser? = nil) {
        self.user = user
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case user
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(user, forKey: .user)
    }
}

