//
// IdentifyResponseUserAuthMethodsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct IdentifyResponseUserAuthMethodsInner: Codable, JSONEncodable, Hashable {

    public enum Kind: String, Codable, CaseIterable {
        case phone = "phone"
        case passkey = "passkey"
        case email = "email"
    }
    public var isVerified: Bool
    public var kind: Kind

    public init(isVerified: Bool, kind: Kind) {
        self.isVerified = isVerified
        self.kind = kind
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isVerified = "is_verified"
        case kind
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(isVerified, forKey: .isVerified)
        try container.encode(kind, forKey: .kind)
    }
}

