//
// ProcessRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ProcessRequest: Codable, JSONEncodable, Hashable {

    public enum FixtureResult: String, Codable, CaseIterable {
        case fail = "fail"
        case pass = "pass"
        case manualReview = "manual_review"
        case stepUp = "step_up"
        case useRulesOutcome = "use_rules_outcome"
    }
    public var fixtureResult: FixtureResult?

    public init(fixtureResult: FixtureResult? = nil) {
        self.fixtureResult = fixtureResult
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fixtureResult = "fixture_result"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(fixtureResult, forKey: .fixtureResult)
    }
}

