//
// SignupChallengeRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SignupChallengeRequest: Codable, JSONEncodable, Hashable {

    public enum ChallengeKind: String, Codable, CaseIterable {
        case sms = "sms"
        case biometric = "biometric"
        case email = "email"
    }
    public enum Scope: String, Codable, CaseIterable {
        case my1fp = "my1fp"
        case onboarding = "onboarding"
        case auth = "auth"
    }
    public var challengeKind: ChallengeKind
    public var email: SignupChallengeRequestEmail?
    public var phoneNumber: SignupChallengeRequestEmail?
    public var scope: Scope

    public init(challengeKind: ChallengeKind, email: SignupChallengeRequestEmail? = nil, phoneNumber: SignupChallengeRequestEmail? = nil, scope: Scope) {
        self.challengeKind = challengeKind
        self.email = email
        self.phoneNumber = phoneNumber
        self.scope = scope
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case challengeKind = "challenge_kind"
        case email
        case phoneNumber = "phone_number"
        case scope
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(challengeKind, forKey: .challengeKind)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(phoneNumber, forKey: .phoneNumber)
        try container.encode(scope, forKey: .scope)
    }
}

