//
// SkipPasskeyRegisterRequestContext.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SkipPasskeyRegisterRequestContext: Codable, JSONEncodable, Hashable {

    public enum ClientType: String, Codable, CaseIterable {
        case web = "web"
        case mobile = "mobile"
    }
    public var attempts: [SkipPasskeyRegisterRequestContextAttemptsInner]
    public var clientType: ClientType
    public var numAttempts: Int64
    public var reason: String

    public init(attempts: [SkipPasskeyRegisterRequestContextAttemptsInner], clientType: ClientType, numAttempts: Int64, reason: String) {
        self.attempts = attempts
        self.clientType = clientType
        self.numAttempts = numAttempts
        self.reason = reason
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attempts
        case clientType = "client_type"
        case numAttempts = "num_attempts"
        case reason
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(attempts, forKey: .attempts)
        try container.encode(clientType, forKey: .clientType)
        try container.encode(numAttempts, forKey: .numAttempts)
        try container.encode(reason, forKey: .reason)
    }
}

