//
// SkipPasskeyRegisterRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SkipPasskeyRegisterRequest: Codable, JSONEncodable, Hashable {

    public var context: SkipPasskeyRegisterRequestContext?

    public init(context: SkipPasskeyRegisterRequestContext? = nil) {
        self.context = context
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case context
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(context, forKey: .context)
    }
}

