//
// SocureDeviceSessionIdRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SocureDeviceSessionIdRequest: Codable, JSONEncodable, Hashable {

    public var deviceSessionId: String

    public init(deviceSessionId: String) {
        self.deviceSessionId = deviceSessionId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case deviceSessionId = "device_session_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(deviceSessionId, forKey: .deviceSessionId)
    }
}

