//
// StytchTelemetryRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct StytchTelemetryRequest: Codable, JSONEncodable, Hashable {

    public var telemetryId: String

    public init(telemetryId: String) {
        self.telemetryId = telemetryId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case telemetryId = "telemetry_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(telemetryId, forKey: .telemetryId)
    }
}

