//
// AuthRequirementsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AuthRequirementsResponse: Codable, JSONEncodable, Hashable {

    public var allRequirements: [AuthRequirementsResponseAllRequirementsInner]

    public init(allRequirements: [AuthRequirementsResponseAllRequirementsInner]) {
        self.allRequirements = allRequirements
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case allRequirements = "all_requirements"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(allRequirements, forKey: .allRequirements)
    }
}

