//
// ConsentRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ConsentRequest: Codable, JSONEncodable, Hashable {

    public var consentLanguageText: String
    public var mlConsent: Bool?

    public init(consentLanguageText: String, mlConsent: Bool? = nil) {
        self.consentLanguageText = consentLanguageText
        self.mlConsent = mlConsent
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case consentLanguageText = "consent_language_text"
        case mlConsent = "ml_consent"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(consentLanguageText, forKey: .consentLanguageText)
        try container.encodeIfPresent(mlConsent, forKey: .mlConsent)
    }
}

