//
// CreateOnboardingTimelineRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateOnboardingTimelineRequest: Codable, JSONEncodable, Hashable {

    public var event: String

    public init(event: String) {
        self.event = event
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case event
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(event, forKey: .event)
    }
}

