//
// CreateDeviceAttestationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateDeviceAttestationRequest: Codable, JSONEncodable, Hashable {

    /** base64 encoded attestation */
    public var attestation: String
    /** state from `DeviceAttestationChallengeResponse` */
    public var state: String

    public init(attestation: String, state: String) {
        self.attestation = attestation
        self.state = state
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attestation
        case state
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(attestation, forKey: .attestation)
        try container.encode(state, forKey: .state)
    }
}

