//
// CreateUserTokenRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateUserTokenRequest: Codable, JSONEncodable, Hashable {

    public enum RequestedScope: String, Codable, CaseIterable {
        case auth = "auth"
        case onboarding = "onboarding"
        case my1fp = "my1fp"
        case onboardingComponents = "onboarding_components"
    }
    public var requestedScope: RequestedScope

    public init(requestedScope: RequestedScope) {
        self.requestedScope = requestedScope
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case requestedScope = "requested_scope"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requestedScope, forKey: .requestedScope)
    }
}

