//
// D2pGenerateRequestMetaL10n.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct D2pGenerateRequestMetaL10n: Codable, JSONEncodable, Hashable {

    public var language: String?
    public var locale: String?

    public init(language: String? = nil, locale: String? = nil) {
        self.language = language
        self.locale = locale
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case language
        case locale
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(language, forKey: .language)
        try container.encodeIfPresent(locale, forKey: .locale)
    }
}

