//
// D2pStatusResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct D2pStatusResponse: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable {
        case waiting = "waiting"
        case inProgress = "in_progress"
        case canceled = "canceled"
        case failed = "failed"
        case completed = "completed"
    }
    public var meta: D2pGenerateRequestMeta?
    public var status: Status

    public init(meta: D2pGenerateRequestMeta? = nil, status: Status) {
        self.meta = meta
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case meta
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(meta, forKey: .meta)
        try container.encode(status, forKey: .status)
    }
}

