//
// GetSdkArgsTokenResponseObConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The public onboarding configuration */
public struct GetSdkArgsTokenResponseObConfig: Codable, JSONEncodable, Hashable {

    public enum Kind: String, Codable, CaseIterable {
        case kyc = "kyc"
        case kyb = "kyb"
        case auth = "auth"
        case document = "document"
    }
    public enum RequiredAuthMethods: String, Codable, CaseIterable {
        case phone = "phone"
        case passkey = "passkey"
        case email = "email"
    }
    public enum Status: String, Codable, CaseIterable {
        case disabled = "disabled"
        case enabled = "enabled"
    }
    public enum SupportedCountries: String, Codable, CaseIterable {
        case tw = "TW"
        case af = "AF"
        case al = "AL"
        case dz = "DZ"
        case _as = "AS"
        case ad = "AD"
        case ao = "AO"
        case ai = "AI"
        case aq = "AQ"
        case ag = "AG"
        case ar = "AR"
        case am = "AM"
        case aw = "AW"
        case au = "AU"
        case at = "AT"
        case az = "AZ"
        case bs = "BS"
        case bh = "BH"
        case bd = "BD"
        case bb = "BB"
        case by = "BY"
        case be = "BE"
        case bz = "BZ"
        case bj = "BJ"
        case bm = "BM"
        case bt = "BT"
        case bo = "BO"
        case bq = "BQ"
        case ba = "BA"
        case bw = "BW"
        case bv = "BV"
        case br = "BR"
        case io = "IO"
        case vg = "VG"
        case bn = "BN"
        case bg = "BG"
        case bf = "BF"
        case bi = "BI"
        case cv = "CV"
        case kh = "KH"
        case cm = "CM"
        case ca = "CA"
        case ky = "KY"
        case cf = "CF"
        case td = "TD"
        case cl = "CL"
        case cn = "CN"
        case hk = "HK"
        case mo = "MO"
        case cx = "CX"
        case cc = "CC"
        case co = "CO"
        case km = "KM"
        case cg = "CG"
        case ck = "CK"
        case cr = "CR"
        case hr = "HR"
        case cu = "CU"
        case cw = "CW"
        case cy = "CY"
        case cz = "CZ"
        case ci = "CI"
        case kp = "KP"
        case cd = "CD"
        case dk = "DK"
        case dj = "DJ"
        case dm = "DM"
        case _do = "DO"
        case ec = "EC"
        case eg = "EG"
        case sv = "SV"
        case gq = "GQ"
        case er = "ER"
        case ee = "EE"
        case sz = "SZ"
        case et = "ET"
        case fk = "FK"
        case fo = "FO"
        case fj = "FJ"
        case fi = "FI"
        case fr = "FR"
        case gf = "GF"
        case pf = "PF"
        case tf = "TF"
        case ga = "GA"
        case gm = "GM"
        case ge = "GE"
        case de = "DE"
        case gh = "GH"
        case gi = "GI"
        case gr = "GR"
        case gl = "GL"
        case gd = "GD"
        case gp = "GP"
        case gu = "GU"
        case gt = "GT"
        case gg = "GG"
        case gn = "GN"
        case gw = "GW"
        case gy = "GY"
        case ht = "HT"
        case hm = "HM"
        case va = "VA"
        case hn = "HN"
        case hu = "HU"
        case _is = "IS"
        case _in = "IN"
        case id = "ID"
        case ir = "IR"
        case iq = "IQ"
        case ie = "IE"
        case im = "IM"
        case il = "IL"
        case it = "IT"
        case jm = "JM"
        case jp = "JP"
        case je = "JE"
        case jo = "JO"
        case kz = "KZ"
        case ke = "KE"
        case ki = "KI"
        case kw = "KW"
        case kg = "KG"
        case la = "LA"
        case lv = "LV"
        case lb = "LB"
        case ls = "LS"
        case lr = "LR"
        case ly = "LY"
        case li = "LI"
        case lt = "LT"
        case lu = "LU"
        case mg = "MG"
        case mw = "MW"
        case my = "MY"
        case mv = "MV"
        case ml = "ML"
        case mt = "MT"
        case mh = "MH"
        case mq = "MQ"
        case mr = "MR"
        case mu = "MU"
        case yt = "YT"
        case mx = "MX"
        case fm = "FM"
        case mc = "MC"
        case mn = "MN"
        case me = "ME"
        case ms = "MS"
        case ma = "MA"
        case mz = "MZ"
        case mm = "MM"
        case na = "NA"
        case nr = "NR"
        case np = "NP"
        case nl = "NL"
        case nc = "NC"
        case nz = "NZ"
        case ni = "NI"
        case ne = "NE"
        case ng = "NG"
        case nu = "NU"
        case nf = "NF"
        case mp = "MP"
        case no = "NO"
        case om = "OM"
        case pk = "PK"
        case pw = "PW"
        case pa = "PA"
        case pg = "PG"
        case py = "PY"
        case pe = "PE"
        case ph = "PH"
        case pn = "PN"
        case pl = "PL"
        case pt = "PT"
        case pr = "PR"
        case qa = "QA"
        case kr = "KR"
        case md = "MD"
        case ro = "RO"
        case ru = "RU"
        case rw = "RW"
        case re = "RE"
        case bl = "BL"
        case sh = "SH"
        case kn = "KN"
        case lc = "LC"
        case mf = "MF"
        case pm = "PM"
        case vc = "VC"
        case ws = "WS"
        case sm = "SM"
        case st = "ST"
        case sa = "SA"
        case sn = "SN"
        case rs = "RS"
        case sc = "SC"
        case sl = "SL"
        case sg = "SG"
        case sx = "SX"
        case sk = "SK"
        case si = "SI"
        case sb = "SB"
        case so = "SO"
        case za = "ZA"
        case gs = "GS"
        case ss = "SS"
        case es = "ES"
        case lk = "LK"
        case ps = "PS"
        case sd = "SD"
        case sr = "SR"
        case sj = "SJ"
        case se = "SE"
        case ch = "CH"
        case sy = "SY"
        case tj = "TJ"
        case th = "TH"
        case mk = "MK"
        case tl = "TL"
        case tg = "TG"
        case tk = "TK"
        case to = "TO"
        case tt = "TT"
        case tn = "TN"
        case tr = "TR"
        case tm = "TM"
        case tc = "TC"
        case tv = "TV"
        case ug = "UG"
        case ua = "UA"
        case ae = "AE"
        case gb = "GB"
        case tz = "TZ"
        case um = "UM"
        case vi = "VI"
        case us = "US"
        case uy = "UY"
        case uz = "UZ"
        case vu = "VU"
        case ve = "VE"
        case vn = "VN"
        case wf = "WF"
        case eh = "EH"
        case ye = "YE"
        case zm = "ZM"
        case zw = "ZW"
        case ax = "AX"
    }
    public var allowInternationalResidents: Bool
    /** allow list of origins permitted to host the embedded flow */
    public var allowedOrigins: [String]?
    public var appClipExperienceId: String
    public var appearance: JSONValue?
    public var canMakeRealDocScanCallsInSandbox: Bool
    public var docScanRequiredIfSsnSkipped: Bool?
    public var isAppClipEnabled: Bool
    public var isInstantAppEnabled: Bool
    public var isKyb: Bool
    public var isLive: Bool
    public var isNoPhoneFlow: Bool
    public var isStepupEnabled: Bool
    public var key: String
    public var kind: Kind
    public var logoUrl: String?
    public var name: String
    public var nidEnabled: Bool?
    public var orgId: String
    public var orgName: String
    public var privacyPolicyUrl: String?
    /** When non-null, the provided auth methods are required to be verified by the playbook. Null  does not mean that no auth is required - it just means the playbook doesn't care which  method is used. */
    public var requiredAuthMethods: [RequiredAuthMethods]?
    public var requiresIdDoc: Bool
    public var status: Status
    public var supportEmail: String?
    public var supportPhone: String?
    public var supportWebsite: String?
    public var supportedCountries: [SupportedCountries]

    public init(allowInternationalResidents: Bool, allowedOrigins: [String]? = nil, appClipExperienceId: String, appearance: JSONValue? = nil, canMakeRealDocScanCallsInSandbox: Bool, docScanRequiredIfSsnSkipped: Bool? = nil, isAppClipEnabled: Bool, isInstantAppEnabled: Bool, isKyb: Bool, isLive: Bool, isNoPhoneFlow: Bool, isStepupEnabled: Bool, key: String, kind: Kind, logoUrl: String? = nil, name: String, nidEnabled: Bool? = nil, orgId: String, orgName: String, privacyPolicyUrl: String? = nil, requiredAuthMethods: [RequiredAuthMethods]? = nil, requiresIdDoc: Bool, status: Status, supportEmail: String? = nil, supportPhone: String? = nil, supportWebsite: String? = nil, supportedCountries: [SupportedCountries]) {
        self.allowInternationalResidents = allowInternationalResidents
        self.allowedOrigins = allowedOrigins
        self.appClipExperienceId = appClipExperienceId
        self.appearance = appearance
        self.canMakeRealDocScanCallsInSandbox = canMakeRealDocScanCallsInSandbox
        self.docScanRequiredIfSsnSkipped = docScanRequiredIfSsnSkipped
        self.isAppClipEnabled = isAppClipEnabled
        self.isInstantAppEnabled = isInstantAppEnabled
        self.isKyb = isKyb
        self.isLive = isLive
        self.isNoPhoneFlow = isNoPhoneFlow
        self.isStepupEnabled = isStepupEnabled
        self.key = key
        self.kind = kind
        self.logoUrl = logoUrl
        self.name = name
        self.nidEnabled = nidEnabled
        self.orgId = orgId
        self.orgName = orgName
        self.privacyPolicyUrl = privacyPolicyUrl
        self.requiredAuthMethods = requiredAuthMethods
        self.requiresIdDoc = requiresIdDoc
        self.status = status
        self.supportEmail = supportEmail
        self.supportPhone = supportPhone
        self.supportWebsite = supportWebsite
        self.supportedCountries = supportedCountries
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case allowInternationalResidents = "allow_international_residents"
        case allowedOrigins = "allowed_origins"
        case appClipExperienceId = "app_clip_experience_id"
        case appearance
        case canMakeRealDocScanCallsInSandbox = "can_make_real_doc_scan_calls_in_sandbox"
        case docScanRequiredIfSsnSkipped = "doc_scan_required_if_ssn_skipped"
        case isAppClipEnabled = "is_app_clip_enabled"
        case isInstantAppEnabled = "is_instant_app_enabled"
        case isKyb = "is_kyb"
        case isLive = "is_live"
        case isNoPhoneFlow = "is_no_phone_flow"
        case isStepupEnabled = "is_stepup_enabled"
        case key
        case kind
        case logoUrl = "logo_url"
        case name
        case nidEnabled = "nid_enabled"
        case orgId = "org_id"
        case orgName = "org_name"
        case privacyPolicyUrl = "privacy_policy_url"
        case requiredAuthMethods = "required_auth_methods"
        case requiresIdDoc = "requires_id_doc"
        case status
        case supportEmail = "support_email"
        case supportPhone = "support_phone"
        case supportWebsite = "support_website"
        case supportedCountries = "supported_countries"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(allowInternationalResidents, forKey: .allowInternationalResidents)
        try container.encodeIfPresent(allowedOrigins, forKey: .allowedOrigins)
        try container.encode(appClipExperienceId, forKey: .appClipExperienceId)
        try container.encodeIfPresent(appearance, forKey: .appearance)
        try container.encode(canMakeRealDocScanCallsInSandbox, forKey: .canMakeRealDocScanCallsInSandbox)
        try container.encodeIfPresent(docScanRequiredIfSsnSkipped, forKey: .docScanRequiredIfSsnSkipped)
        try container.encode(isAppClipEnabled, forKey: .isAppClipEnabled)
        try container.encode(isInstantAppEnabled, forKey: .isInstantAppEnabled)
        try container.encode(isKyb, forKey: .isKyb)
        try container.encode(isLive, forKey: .isLive)
        try container.encode(isNoPhoneFlow, forKey: .isNoPhoneFlow)
        try container.encode(isStepupEnabled, forKey: .isStepupEnabled)
        try container.encode(key, forKey: .key)
        try container.encode(kind, forKey: .kind)
        try container.encodeIfPresent(logoUrl, forKey: .logoUrl)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(nidEnabled, forKey: .nidEnabled)
        try container.encode(orgId, forKey: .orgId)
        try container.encode(orgName, forKey: .orgName)
        try container.encodeIfPresent(privacyPolicyUrl, forKey: .privacyPolicyUrl)
        try container.encodeIfPresent(requiredAuthMethods, forKey: .requiredAuthMethods)
        try container.encode(requiresIdDoc, forKey: .requiresIdDoc)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(supportEmail, forKey: .supportEmail)
        try container.encodeIfPresent(supportPhone, forKey: .supportPhone)
        try container.encodeIfPresent(supportWebsite, forKey: .supportWebsite)
        try container.encode(supportedCountries, forKey: .supportedCountries)
    }
}

