//
// GetUserTokenResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetUserTokenResponse: Codable, JSONEncodable, Hashable {

    public enum Scopes: String, Codable, CaseIterable {
        case signUp = "sign_up"
        case auth = "auth"
        case basicProfile = "basic_profile"
        case sensitiveProfile = "sensitive_profile"
        case handoff = "handoff"
        case vaultData = "vault_data"
        case explicitAuth = "explicit_auth"
    }
    public var expiresAt: Date
    public var scopes: [Scopes]

    public init(expiresAt: Date, scopes: [Scopes]) {
        self.expiresAt = expiresAt
        self.scopes = scopes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case expiresAt = "expires_at"
        case scopes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(expiresAt, forKey: .expiresAt)
        try container.encode(scopes, forKey: .scopes)
    }
}

