//
// HostedValidateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct HostedValidateResponse: Codable, JSONEncodable, Hashable {

    /** An cryptographically generated auth token to authenticate a session */
    public var validationToken: String

    public init(validationToken: String) {
        self.validationToken = validationToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case validationToken = "validation_token"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(validationToken, forKey: .validationToken)
    }
}

