//
// IdentifyVerifyResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct IdentifyVerifyResponse: Codable, JSONEncodable, Hashable {

    /** An cryptographically generated auth token to authenticate a session */
    public var authToken: String

    public init(authToken: String) {
        self.authToken = authToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case authToken = "auth_token"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(authToken, forKey: .authToken)
    }
}

