//
// LiteIdentifyRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LiteIdentifyRequest: Codable, JSONEncodable, Hashable {

    public var email: String?
    public var phoneNumber: String?

    public init(email: String? = nil, phoneNumber: String? = nil) {
        self.email = email
        self.phoneNumber = phoneNumber
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case phoneNumber = "phone_number"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(phoneNumber, forKey: .phoneNumber)
    }
}

