//
// LiteIdentifyResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LiteIdentifyResponse: Codable, JSONEncodable, Hashable {

    public var userFound: Bool

    public init(userFound: Bool) {
        self.userFound = userFound
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userFound = "user_found"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(userFound, forKey: .userFound)
    }
}

