//
// LoginChallengeResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LoginChallengeResponse: Codable, JSONEncodable, Hashable {

    public var challengeData: LoginChallengeResponseChallengeData
    public var error: String?

    public init(challengeData: LoginChallengeResponseChallengeData, error: String? = nil) {
        self.challengeData = challengeData
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case challengeData = "challenge_data"
        case error
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(challengeData, forKey: .challengeData)
        try container.encodeIfPresent(error, forKey: .error)
    }
}

