//
// LoginChallengeRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LoginChallengeRequest: Codable, JSONEncodable, Hashable {

    public enum ChallengeKind: String, Codable, CaseIterable {
        case sms = "sms"
        case biometric = "biometric"
        case email = "email"
    }
    public var challengeKind: ChallengeKind

    public init(challengeKind: ChallengeKind) {
        self.challengeKind = challengeKind
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case challengeKind = "challenge_kind"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(challengeKind, forKey: .challengeKind)
    }
}

