//
// OnboardingSessionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct OnboardingSessionResponse: Codable, JSONEncodable, Hashable {

    public var bootstrapData: JSONValue
    public var key: String?

    public init(bootstrapData: JSONValue, key: String? = nil) {
        self.bootstrapData = bootstrapData
        self.key = key
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bootstrapData = "bootstrap_data"
        case key
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(bootstrapData, forKey: .bootstrapData)
        try container.encodeIfPresent(key, forKey: .key)
    }
}

