//
// RegisterAuthMethodRequirement.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RegisterAuthMethodRequirement: Codable, JSONEncodable, Hashable {

    public enum Kind: String, Codable, CaseIterable {
        case registerAuthMethod = "register_auth_method"
    }
    public enum AuthMethodKind: String, Codable, CaseIterable {
        case phone = "phone"
        case email = "email"
        case passkey = "passkey"
    }
    public var kind: Kind
    public var isMet: Bool
    public var authMethodKind: AuthMethodKind

    public init(kind: Kind, isMet: Bool, authMethodKind: AuthMethodKind) {
        self.kind = kind
        self.isMet = isMet
        self.authMethodKind = authMethodKind
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case kind
        case isMet = "is_met"
        case authMethodKind = "auth_method_kind"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(kind, forKey: .kind)
        try container.encode(isMet, forKey: .isMet)
        try container.encode(authMethodKind, forKey: .authMethodKind)
    }
}

