//
// SignupChallengeRequestEmail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SignupChallengeRequestEmail: Codable, JSONEncodable, Hashable {

    public var isBootstrap: Bool
    public var value: String

    public init(isBootstrap: Bool, value: String) {
        self.isBootstrap = isBootstrap
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isBootstrap = "is_bootstrap"
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(isBootstrap, forKey: .isBootstrap)
        try container.encode(value, forKey: .value)
    }
}

