//
// SkipPasskeyRegisterRequestContextAttemptsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SkipPasskeyRegisterRequestContextAttemptsInner: Codable, JSONEncodable, Hashable {

    public var elapsedTimeInOsPromptMs: Int64?
    public var errorMessage: String

    public init(elapsedTimeInOsPromptMs: Int64? = nil, errorMessage: String) {
        self.elapsedTimeInOsPromptMs = elapsedTimeInOsPromptMs
        self.errorMessage = errorMessage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case elapsedTimeInOsPromptMs = "elapsed_time_in_os_prompt_ms"
        case errorMessage = "error_message"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(elapsedTimeInOsPromptMs, forKey: .elapsedTimeInOsPromptMs)
        try container.encode(errorMessage, forKey: .errorMessage)
    }
}

