//
// VaultDI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum VaultDI: String, Codable, CaseIterable {
    case idPeriodFirstName = "id.first_name"
    case idPeriodMiddleName = "id.middle_name"
    case idPeriodLastName = "id.last_name"
    case idPeriodDob = "id.dob"
    case idPeriodSsn4 = "id.ssn4"
    case idPeriodSsn9 = "id.ssn9"
    case idPeriodAddressLine1 = "id.address_line1"
    case idPeriodAddressLine2 = "id.address_line2"
    case idPeriodCity = "id.city"
    case idPeriodState = "id.state"
    case idPeriodZip = "id.zip"
    case idPeriodCountry = "id.country"
    case idPeriodEmail = "id.email"
    case idPeriodPhoneNumber = "id.phone_number"
    case idPeriodUsLegalStatus = "id.us_legal_status"
    case idPeriodVisaKind = "id.visa_kind"
    case idPeriodVisaExpirationDate = "id.visa_expiration_date"
    case idPeriodNationality = "id.nationality"
    case idPeriodCitizenships = "id.citizenships"
    case idPeriodDriversLicenseNumber = "id.drivers_license_number"
    case idPeriodDriversLicenseState = "id.drivers_license_state"
    case idPeriodItin = "id.itin"
    case idPeriodUsTaxId = "id.us_tax_id"
    case customPeriodStar = "custom.*"
    case investorProfilePeriodEmploymentStatus = "investor_profile.employment_status"
    case investorProfilePeriodOccupation = "investor_profile.occupation"
    case investorProfilePeriodEmployer = "investor_profile.employer"
    case investorProfilePeriodAnnualIncome = "investor_profile.annual_income"
    case investorProfilePeriodNetWorth = "investor_profile.net_worth"
    case investorProfilePeriodInvestmentGoals = "investor_profile.investment_goals"
    case investorProfilePeriodRiskTolerance = "investor_profile.risk_tolerance"
    case investorProfilePeriodDeclarations = "investor_profile.declarations"
    case investorProfilePeriodBrokerageFirmEmployer = "investor_profile.brokerage_firm_employer"
    case investorProfilePeriodSeniorExecutiveSymbols = "investor_profile.senior_executive_symbols"
    case investorProfilePeriodFamilyMemberNames = "investor_profile.family_member_names"
    case investorProfilePeriodPoliticalOrganization = "investor_profile.political_organization"
    case investorProfilePeriodFundingSources = "investor_profile.funding_sources"
}
